---
title: "Trust Analysis 2024"
author: "Jordan"
date: "2023-11-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(tree)
library(dplyr)
library(randomForest)
library(rpart.plot)
```

```{r}
trust_2023_raw_data <- read_csv("trust_2023_raw_data.csv")
```
# Credibility:

```{r}
believe_real_data <- trust_2023_raw_data %>%
  filter(name == "I believe the visualization shows real data.") %>%
  select(-c(...1, subfolder, name, session_id, category, question_type, cluster, image, image_new, title, `title location`, likertscale, starts_with("mem"))) %>% head(600)
```

```{r}
believe_prelim_tree <- rpart(response ~. , data = believe_real_data, method="class")
```

```{r}
rpart.plot(believe_prelim_tree, type = 4, clip.right.labs = FALSE, extra=102)
```

```{r}
believe_real_data <- na.omit(believe_real_data)
#believe_prelim_tree$name <- droplevels(believe_prelim_tree$name, exclude = "")

bag_credibility_bagged = randomForest(response~time,
                       data = believe_real_data, 
                       importance = TRUE)
varImpPlot(bag_Q10S_bagged)

bag_credibility_randomforests = randomForest(response ~ ., 
                       data = believe_real_data, 
                       importance = TRUE)
# Print the model
varImpPlot(bag_Q10S_randomforests)


```


#Clarity:
#Reliability
#Familiarity
#Confidence


for each of these variable how are people's responses distributed on the different facets. if we test on different subjects are fgetting similar groupings. for each of the groups 
1. plot each observation that falls into each leaf.
for each leaf node



